# Imports

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

# Home-made methods

## Gauss elimination

It is illustrative to start writing our code working on a specific example, and then translate it into a function that accepts any matrix and vector

In [11]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

# recast to avoid problems if a and b are integer ndarrays (as in this case)
a = a.astype(np.float64)
b = b.astype(np.float64)

# find the coefficient to set to 0 the first element of the second row
i=0
a[i+1:,0] -= a[i+1:, i]/a[i, i] #the 0 in a[i+1:,0] is needed cause the RHS is just a vector, for now

a

array([[1., 2., 3.],
       [0., 3., 4.],
       [0., 8., 9.]])

In [12]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

a = a.astype(np.float64)
b = b.astype(np.float64)

# use that coefficient to manipulate the second row of the matrix
# notice we dropped the aforementioned 0
i=0
a[i+1] -= a[i+1, i]/a[i, i] * a[i]

a

array([[1., 2., 3.],
       [0., 1., 1.],
       [7., 8., 9.]])

In [14]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

a = a.astype(np.float64)
b = b.astype(np.float64)

# do the same to all the rows of the matrix after the first
# by building a matrix from the outer product of an array of coefficients
# and the first row of the matrix
i=0
a[i+1:] -= np.outer(a[i+1:, i]/a[i, i], a[i])

a

array([[  1.,   2.,   3.],
       [  0.,   1.,   1.],
       [  0.,  -6., -12.]])

In [15]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

a = a.astype(np.float64)
b = b.astype(np.float64)

# repeat for all the rows of the matrix until the second to last
# also apply the same transformations to the b vector
for i in range(len(a)-1):
    b[i+1:] -= a[i+1:,i]/a[i,i] * b[i]
    a[i+1:] -= np.outer(a[i+1:,i]/a[i,i], a[i])
    print("i=", i)
    print("a=\n", a)
    print("b=\n", b)
    print()
    
a

i= 0
a=
 [[  1.   2.   3.]
 [  0.   1.   1.]
 [  0.  -6. -12.]]
b=
 [  9.  -6. -59.]

i= 1
a=
 [[ 1.  2.  3.]
 [ 0.  1.  1.]
 [ 0.  0. -6.]]
b=
 [  9.  -6. -95.]



array([[ 1.,  2.,  3.],
       [ 0.,  1.,  1.],
       [ 0.,  0., -6.]])

In [52]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

a = a.astype(np.float64)
b = b.astype(np.float64)

# Notice that we did not bother to normalize all rows in such a way 
# that the first non-zero element is 1.
# We will have to be mindful of this in the following.
for i in range(len(a)-1):
    b[i+1:] -= a[i+1:,i]/a[i,i] * b[i]
    a[i+1:] -= np.outer(a[i+1:,i]/a[i,i], a[i])
    print("i=", i)
    print("a=\n", a)
    print("b=\n", b)
    print()

i= 0
a=
 [[  1.   2.   3.]
 [  0.   1.   1.]
 [  0.  -6. -12.]]
b=
 [  9.  -6. -59.]

i= 1
a=
 [[ 1.  2.  3.]
 [ 0.  1.  1.]
 [ 0.  0. -6.]]
b=
 [  9.  -6. -95.]



In [55]:
# Small digression on looping indeces backward, as required in the back substitution
for i in range(5, -1, -1):
    print(i)

print()
    
for i in range(len(b)-1, -1, -1):
    print(i)

5
4
3
2
1
0

2
1
0


In [57]:
# Implement the back substitution
print("starting backsub")
x = np.zeros(len(b))
for i in range(len(b)-1, -1, -1):
    print(x)
    x[i] = (b[i] - np.sum(x*a[i]))/a[i,i]
print()

# Compare our solution with a different implementation
print("result")
print(x)

a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])
print(np.linalg.solve(a,b))

starting backsub
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0.         0.         1.66666667 0.        ]
[0.         0.         1.66666667 0.        ]

result
[1.66666667 0.         1.66666667 0.        ]
[  5.16666667 -21.83333333  15.83333333]


In [58]:
# Start packing what we just did in a function
def gauss_solve(a, b):
    a = a.astype(np.float64)
    b = b.astype(np.float64)

    for i in range(len(a)-1):        
        b[i+1:] -= a[i+1:,i]/a[i,i] * b[i]
        a[i+1:] -= np.outer(a[i+1:,i]/a[i,i], a[i])
        print("i=", i)
        print("a=\n", a)
        print("b=\n", b)
        print()
        
    print("starting backsub")
    x = np.zeros(len(b))
    for i in range(len(b)-1, -1, -1):
        print(x)
        x[i] = (b[i] - np.sum(x*a[i]))/a[i,i]
    print()

    print("result")
    return x

In [59]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

print(gauss_solve(a, b))

i= 0
a=
 [[  1.   2.   3.]
 [  0.   1.   1.]
 [  0.  -6. -12.]]
b=
 [  9.  -6. -59.]

i= 1
a=
 [[ 1.  2.  3.]
 [ 0.  1.  1.]
 [ 0.  0. -6.]]
b=
 [  9.  -6. -95.]

starting backsub
[0. 0. 0.]
[ 0.          0.         15.83333333]
[  0.         -21.83333333  15.83333333]

result
[  5.16666667 -21.83333333  15.83333333]


In [60]:
#Add some extra flags, and error management
def gauss_solve(a, b, dbg=False):
    if(dbg):
        np_x = np.linalg.solve(a,b)
    
    a = a.astype(np.float64)
    b = b.astype(np.float64)

    for i in range(len(a)-1):
        if(a[i,i]==0):
            raise ValueError("0 encoutered on the diagonal. Use another solver.")
        
        b[i+1:] -= a[i+1:,i]/a[i,i] * b[i]
        a[i+1:] -= np.outer(a[i+1:,i]/a[i,i], a[i])
        
        if(dbg):
            print("i=", i)
            print("a=\n", a)
            print("b=\n", b)
            print()
            
    if(dbg):
        print("starting backsub")
        print()
        
    x = np.zeros(len(b))
    for i in range(len(b)-1, -1, -1):
        if(dbg):
            print(x)
        x[i] = (b[i] - np.sum(x*a[i]))/a[i,i]
    if(dbg):
        print(x)
        print()
        return x, np_x

    return x

In [61]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

print(gauss_solve(a, b))
print(gauss_solve(a, b, False))
print(gauss_solve(a, b, dbg=False))

[  5.16666667 -21.83333333  15.83333333]
[  5.16666667 -21.83333333  15.83333333]
[  5.16666667 -21.83333333  15.83333333]


In [46]:
a=np.array([
    [1,2,3],
    [1,3,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

gauss_solve(a, b, True)


i= 0
a=
 [[  1.   2.   3.]
 [  0.   1.   1.]
 [  0.  -6. -12.]]
b=
 [  9.  -6. -59.]

i= 1
a=
 [[ 1.  2.  3.]
 [ 0.  1.  1.]
 [ 0.  0. -6.]]
b=
 [  9.  -6. -95.]

starting backsub

[0. 0. 0.]
[ 0.          0.         15.83333333]
[  0.         -21.83333333  15.83333333]
[  5.16666667 -21.83333333  15.83333333]



(array([  5.16666667, -21.83333333,  15.83333333]),
 array([  5.16666667, -21.83333333,  15.83333333]))

Not all matrices can be treated with this simple algorithm

In [49]:
a=np.array([
    [1,2,3],
    [1,2,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

gauss_solve(a, b, True)

i= 0
a=
 [[  1.   2.   3.]
 [  0.   0.   1.]
 [  0.  -6. -12.]]
b=
 [  9.  -6. -59.]



ValueError: 0 encoutered on the diagonal. Use another solver.

## Gauss with partial pivoting

In [65]:
# small digression on advanced indexing, which we use to swap the position of rows
# when we implement the pivoting
# https://numpy.org/doc/stable/user/basics.indexing.html
a=np.array([
    [1,2,3],
    [1,2,4],
    [7,8,9]
])

a[[1, 2]] = a[[2, 1]]

a

array([[1, 2, 3],
       [7, 8, 9],
       [1, 2, 4]])

In [68]:
def gauss_solve_pivot(a, b, dbg=False):
    if(dbg):
        np_x = np.linalg.solve(a,b)
    
    a = a.astype(np.float64)
    b = b.astype(np.float64)

    for i in range(len(a)-1):
        # Notice the "i + ". It is there cause len(a[i:,i]) = len(a) - i
        new_i = i + np.argmax(a[i:,i]) 
        a[[i, new_i]] = a[[new_i, i]]
        b[[i, new_i]] = b[[new_i, i]]
        
        b[i+1:] -= a[i+1:,i]/a[i,i] * b[i]
        a[i+1:] -= np.outer(a[i+1:,i]/a[i,i], a[i])
        
        if(dbg):
            print("i=", i)
            print("a=\n", a)
            print("b=\n", b)
            print()
            
    if(dbg):
        print("starting backsub")
        
    x = np.zeros(len(b))
    for i in range(len(b)-1, -1, -1):
        x[i] = (b[i] - np.sum(x*a[i]))/a[i,i]
    
    if(dbg):
        return x, np_x

    return x

In [69]:
a=np.array([
    [1,2,3],
    [1,2,4],
    [7,8,9]
])
b=np.array([9, 3, 4])

gauss_solve_pivot(a, b, True)

i= 0
a=
 [[7.         8.         9.        ]
 [0.         0.85714286 2.71428571]
 [0.         0.85714286 1.71428571]]
b=
 [4.         2.42857143 8.42857143]

i= 1
a=
 [[ 7.          8.          9.        ]
 [ 0.          0.85714286  2.71428571]
 [ 0.          0.         -1.        ]]
b=
 [4.         2.42857143 6.        ]

starting backsub


(array([-16.66666667,  21.83333333,  -6.        ]),
 array([-16.66666667,  21.83333333,  -6.        ]))

It is now trivial to solve the exercise on slide 44

In [71]:
a=np.array([
    [ 4,-1,-1,-1],
    [-1, 3, 0,-1],
    [-1, 0, 3,-1],
    [-1,-1,-1, 4],
])
b=np.array([5, 0, 5, 0])

gauss_solve_pivot(a, b)

array([3.        , 1.66666667, 3.33333333, 2.        ])

## numpy ndarray and linalg

In [85]:
#ndarrays are defined as
a=np.array([
    [1,2,3],
    [1,2,4],
    [7,8,9]
])
b=np.array([5, 0, 5,])

In [74]:
a

array([[1, 2, 3],
       [1, 2, 4],
       [7, 8, 9]])

In [75]:
# you can slice them
a[:,1]

array([2, 2, 8])

In [82]:
# Transpose matrix
a.T

array([[1, 1, 7],
       [2, 2, 8],
       [3, 4, 9]])

In [87]:
# you can't transpose a 1d vector
print(b)
print(b.T)

[5 0 5]
[5 0 5]


In [92]:
# a few types of multiplications are defined
# make sure to use the correct one

a = np.array([1, 2, 3])
print(a)
print(b)

[1 2 3]
[5 0 5]


In [93]:
# element-wise
print(b*a)

[ 5  0 15]


In [94]:
# inner
np.dot(b,a)

20

In [95]:
# inner
np.outer(b,a)

array([[ 5, 10, 15],
       [ 0,  0,  0],
       [ 5, 10, 15]])

In [97]:
# matrix multiplication
a=np.array([
    [1,2,3],
    [1,2,4],
    [7,8,9]
])
b=np.array([5, 0, 5,])

a@b

array([20, 25, 80])

In [105]:
# since .T doens't work as one might naively expect on 1d arrays
# the matrix product of two arrays might not be what one expects

a = np.array([1, 2, 3])

print(a@b)
print(a.T@b)
print(a@b.T)

print()

# some functions are defined for you
print(np.dot(a,b))
print(np.outer(a,b))

20
20
20

20
[[ 5  0  5]
 [10  0 10]
 [15  0 15]]


In [114]:
# or you can recast the 1d arrays into 2d arrays
print("1d\n", a)
print("column\n", np.reshape(a, (3,1)))
print("row\n", np.reshape(a, (1,3)))

1d
 [1 2 3]
column
 [[1]
 [2]
 [3]]
row
 [[1 2 3]]


In [121]:
# and manipulate them as "expected"
print(np.reshape(a, (3,1)) @ np.reshape(b, (1,3)))
print(np.reshape(a, (1,3)) @ np.reshape(b, (3,1)))

[[ 5  0  5]
 [10  0 10]
 [15  0 15]]
[[20]]


In [125]:
# linear algebra operations can be performed with linalg
a=np.array([
    [1,2,3],
    [1,2,4],
    [7,8,9]
])
b=np.array([5, 0, 5,])


# inverse
np.linalg.inv(a)

array([[-2.33333333,  1.        ,  0.33333333],
       [ 3.16666667, -2.        , -0.16666667],
       [-1.        ,  1.        , -0.        ]])

In [126]:
#determinant
np.linalg.det(a)

6.0

In [127]:
# extract eigenvectors and eigenvalues
np.linalg.eig(a)

(array([13.90136774, -0.26352478, -1.63784296]),
 array([[-0.26184976, -0.47726026, -0.26247798],
        [-0.32716447,  0.810583  , -0.68029833],
        [-0.90796372, -0.33937861,  0.68432412]]))

In [128]:
# or just the eigenvalues, and try to get the det from them
print(np.linalg.eigvals(a))
np.prod(np.linalg.eigvals(a))

[13.90136774 -0.26352478 -1.63784296]


6.00000000000001

In [129]:
# Solve linear problems (without re-implementing the algorithms yourself)
np.linalg.solve(a,b)

array([-10.,  15.,  -5.])