## Linear algebra

#### scipy.linalg documentation at https://docs.scipy.org/doc/scipy/reference/linalg.html

### Gaussian elimination

In [ ]:
# implementing my own code to solve a linear system with 
# Gaussian elimination (no pivoting)

import numpy as np
from numpy.linalg import solve

def linear_solve_gauss(A,b):

    # Solve linear system Ax = b via 
    # Gauss elimination

    demomode = False
    
    N = len(b)
    
    for i in range(N):
        #print(i)
        
        # Normalize diagonal to 1.
        fact = A[i,i]
        A[i,:] /= fact
        b[i] /= fact
        
        for j in range(i+1,N):
            # Subract upper rows, multiplied by suitable 
            # factor, to generate an upper diagonal matrix
            # At the end of each loop, column i (set by loop above) 
            # has become (1, 0, .... , 0)  
            fact = A[j,i]
            A[j,:] -= fact*A[i,:]
            b[j] -= fact*b[i]
        
        if (demomode):
            print( ' ' )
            print('i = ', i)
            print('A=', '\n', A)
            
    # Checking that I did it right
    if (demomode):
        print(' ')
        print('After Gauss elimination')
        print('A = ', '\n', A)
        print( ' ' )
        print('b = ', b)
        print( ' ')
    
   
    # Final step: backsubstitution
    
    # Initialize solution vector
    x = np.zeros(len(b))    
    # Gets last solution, x_(N-1)
    x[N-1] = b[N-1]/A[N-1,N-1]
    
    # Proceed backward, line by line
    for i in range(N-2,-1,-1):
        v = np.dot(A[i,i+1:N],x[i+1:N])
        #if (i==1): print(i, i+1, N-1, A[i,i+1:N])
        x[i] = (b[i] - v)/A[i,i]
    
    return x

In [111]:
# Create example for testing

A = [ [2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]]
A = np.array(A,dtype=float)
print(A)

b = [-4, 3, 9, 7]
b = np.array(b,dtype=float)
#print(b)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [ ]:
x = linear_solve_gauss(A,b)

#print(A)

print('The solution vector x is')
print(x)

### Gaussian elimination with pivoting

In [1]:
# Adding pivoting to the previous code

import numpy as np
from numpy.linalg import solve

def linsolve_gauss_pivot(A,b):

    # Solve linear system Ax = b via 
    # Gauss elimination with pivoting

    demomode = False
    
    N = len(b)
    
    for i in range(N):
                    
        # Partial pivoting
        #######################    
        # Collecting elements of column i in vector 'col'
        col = abs(A[:,i]) 
        # Find max element in col (I can of course also perform this and 
        # the previous step in a single line)
        ind = np.argmax(col)
        # If index of max is not the current i in the loop, swap rows
        if (ind > i):
            # Swap
            A[ [i,ind] ] = A[ [ind,i] ]
            b[ [i,ind] ] = b[ [ind,i] ]
        
        if demomode:
            print('\n', 'After pivoting')
            print()
            print('i = ', i)
            print('A=', '\n', A)
            print( ' ' )
            print('b = ', b)
            print( ' ')
        
        # Normalize diagonal to 1.
        fact = A[i,i]
        A[i,:] /= fact
        b[i] /= fact
        
        for j in range(i+1,N):
            # Subract upper rows, multiplied by suitable 
            # factor, to generate an upper diagonal matrix
            # At the end of each loop, column i (set by loop above) 
            # has become (1, 0, .... , 0)  
            fact = A[j,i]
            A[j,:] -= fact*A[i,:]
            b[j] -= fact*b[i]
            
        # Checking that I did it right
        if demomode:
            print(' ')
            print('After Gauss elimination')
            print('A = ', '\n', A)
            print( ' ' )
            print('b = ', b)
            print( ' ')
    
    
    # Final step: backsubstitution
    
    # Initialize solution vector
    x = np.zeros(len(b))    
    # Gets last solution, x_(N-1)
    x[N-1] = b[N-1]/A[N-1,N-1]
    
    # Proceed backward, line by line
    for i in range(N-2,-1,-1):
        v = np.dot(A[i,i+1:N],x[i+1:N])
        #if (i==1): print(i, i+1, N-1, A[i,i+1:N])
        x[i] = (b[i] - v)/A[i,i]
    
    return x


In [2]:
# Testing example for pivoting

A = [ [0, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]]
A = np.array(A,dtype=float)
#print(A)

b = [-4, 3, 9, 7]
b = np.array(b,dtype=float)
#print(b)

In [3]:
x = linsolve_gauss_pivot(A,b)
print(x)

[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


In [ ]:
print( (np.dot(A,x)-b) )

In [4]:
# Cross checking against python solve
x = solve(A,b)
print(x)

[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


In [ ]:
# Another test

A = [ [0, 1, 4, 1], [3, 0, -1, -1], [1, -4, 1, 5], [2, -2, 1, 0]]
A = np.array(A,dtype=float)
#print(A)

b = [-4, 3, 9, 7]
b = np.array(b,dtype=float)
#print(b)

In [ ]:
x = linsolve_gauss_pivot(A,b)
print(x)

In [ ]:
x = solve(A,b)
print(x)

In [ ]:
#Check with 5x5 array

A = [ [0, 1, 4, 1,  7], [3, 0, -1, -1, 3], [1, -4, 1, 5, 0], [2, -2, 1, 0, -5], [-6, 3, 12, -10, 4]]
A = np.array(A,dtype=float)
#print(A)

b = [-4, 3, 9, 7, 8]
b = np.array(b,dtype=float)
#print(b)

In [ ]:
x = solve(A,b)
print(x)

In [ ]:
y = linsolve_gauss_pivot(A,b)
print(y)

### LU decomposition

Implementing LU decomposition of an array A. 

A = LU with L = lower triangular, U = upper triangular.

No need to restart from scratch; it can be done by modifying the previous linear solver 
code. L and U are generated using formulae we saw in class, in the same loop used to update 
A with Gauss elimination.

#### Note below if you want to try and implement LU with pivoting 

Important: when we store L and U, we need also to record all the swaps in the pivoting, because the same swaps need to applied to b later on!

Consider for example a 4 x 4 matrix (generalization to NxN is straightforward). Assume you apply partial pivoting to compute U. Represent the row swaps with permutation
matrices P (for later remember that $P^2 = P$).

Then we can write (with the L matrices as defined in class, but we don't normalize the diagonal of U to 1):

$L_2 P_2 L_1 P_1 L_0 P_0 A = U$

1) Show that you can write:

$L'_2 L'_1 L'_0 P_2 P_1 P_0 = L_2 P_2 L_1 P_1 L_0 P_0$,

where

$L'_0 = P_2 P_1 L_0 P^{-1}_1 P^{-1}_2$
$L'_1 = P_2 L_1 P^{-1}_2$
$L'_2 = L_2$

Note also that the L' arrays are lower triangular, hence their inverse can be obtained trivially by taking the opposite of sub-diagonal elements of $L'$, as seen in class.

Defining $L = {L'}^{-1}_2 {L'}^{-1}_1 {L'}^{-1}_0$ and $P = P_2 P_1 P_0$, the desired LU decomposition is then:

$LU = PA$

2) Based on the previous result, write an algorithm for LU decompostion with pivoting. First get the U array via standard Gauss elimination and record all the swaps in a suitable list. As you proceed, save also the L arrays (Without swapping). At the end, apply the right swaps to get the L' arrays and get the decomposition. 

In [ ]:
import numpy as np
from numpy.linalg import solve
from numpy.linalg import inv

def LUdec(A):

    # Given square array A, finds its LU decomposition
    # Applies partial pivoting
    
    N = len(A)
    
    # Vector of diagonal elements of A
    # To be updated during pivoting
    diag = np.empty(N)
    
    L = np.identity(N)
       
    swap = [ ]
    
    for i in range(N):
    
        # Partial pivoting
        #######################    
        # Find max element in column i
        ind = np.argmax(abs(A[:,i])) 
        # If index of max is not the current i in the loop, swap rows
        if (ind > i):
            # Swap
            A[ [i,ind] ] = A[ [ind,i] ]
            # Recording all permutations in a list.
            # Needed to: permute rows of A, when comparing it with LU, 
            # permute rows of L, permute entries of b when solving Ax = b
            swap.append(ind)
        else:
            swap.append(i)
        #########
        
        norm = A[i,i]
        L[i,i] = 1.0
        
        # Normalizing diagonal of A to 1 for gauss elimination
        #A[i,:] /= norm
        
        for j in range(i+1,N):
            # Updating L
            fact = A[j,i]
            L[j,i] = fact/norm
            # Gauss elimination to get U          
            A[j,:] -= fact*(A[i,:]/norm)
    
    # Applying pivoting permutations to L
    # For each column j in L, I have to interchange rows 
    # for all swaps that were performed at steps j+1...N
    # For example. If am considering column 1, I swap rows 
    # loking at all the permutations from step 2 onwards, but I DON'T
    # apply swaps made at steps 0 and 1.
    for j in range(N-1):
        for i in range(j+1,N):
            p = swap[i]
            L[i,j], L[p,j] = L[p,j], L[i,j]
        
    return L, A, swap

In [ ]:
# Example for testing. No pivoting needed here
A = [ [1, 1, 4, 1], [1, 5, -1, -1], [1, -4, 2, 5], [2, -2, 1, 0]]
A = np.array(A,dtype=float)

#print(A,'\n')

Ain = np.copy(A)

swaps = [ ]

L, U, swaps = LUdec(A)

In [ ]:
disp = np.round(L,2)
print('L=', '\n', disp)
disp = np.round(U,2)
print('U=', '\n', disp)

In [ ]:
print('Checking that LU = A (modulo swaps)', '\n')
LU = np.dot(L,U)
# Redoing the swaps in inverse order
# to "recompose" the original A
for i in range(len(swaps)-1,-1,-1):
    p = swaps[i]
    LU[[i,p]]=LU[[p,i]]
disp = np.round(LU,2)
print('LU = \n',disp)
print(' ')
print('Input A = \n', Ain)

In [ ]:
# Testing example with pivoting

# Testing example for pivoting
A = [ [0, 1, 4, 2], [3, 7, -1, 6], [1, -4, 1, 10], [0, 11, 0, 2]]
A = np.array(A,dtype=float)
#print(A)

Ain = np.copy(A)

L2, U2, swaps = LUdec(A)

In [ ]:
disp = np.round(L2,2)
print('L=', '\n', disp)
disp = np.round(U2,2)
print('U=', '\n', disp)

In [ ]:
print('Checking that LU = A', '\n')
LU = np.dot(L2,U2)
# Redoing the swaps in inverse order
# to "recompose" the original A
for i in range(len(swaps)-1,-1,-1):
    p = swaps[i]
    LU[[i,p]]=LU[[p,i]]
disp = np.round(LU,2)
print(disp)
print(' ')
print(Ain)

### Linear solver, using LU decomposition

Plan: use the LU function implemented above to initially compute and store A = LU. 

Then for any vector b, we can solve Ax = b as LUx = b via double backsubstitution. 

In [ ]:
import numpy as np
from numpy.linalg import solve
from numpy.linalg import inv


class solveinput:
    
    # Defining an object that contains all the input ingredients to solve Ax = b.
    # That is: L, U and the list which records the swaps when doing the LU decomp
    
    def __init__(self,L,U,rec):
        self.lower = L
        self.upper = U
        self.swaps = rec

def LUdec(A):

    # Given square array A, finds its LU decomposition
    # Applies partial pivoting
    
    N = len(A)
    
    # Vector of diagonal elements of A
    # To be updated during pivoting
    diag = np.empty(N)
    
    L = np.identity(N)
       
    swap = [ ]
    
    for i in range(N):
    
        # Partial pivoting
        #######################    
        # Collecting diagonal elements of A in vector 'diag'
        # Find max element in diag 
        ind = np.argmax(abs(A[:,i])) 
        # If index of max is not the current i in the loop, swap rows
        if (ind > i):
            # Swap
            A[ [i,ind] ] = A[ [ind,i] ]
            # Recording all permutations in a list
            # Needed for later
            swap.append(ind)
        else:
            swap.append(i)
        #########
        
        norm = A[i,i]
        L[i,i] = 1.0
        
        for j in range(i+1,N):
            # Updating L
            fact = A[j,i]
            L[j,i] = fact/norm
            # Gauss elimination to get U          
            A[j,:] -= fact*(A[i,:]/norm)
    
    # Applying pivoting permutations to L
    # For each column j in L, I have to interchange rows 
    # for all swaps that were performed at steps j+1...N
    # For example. If am considering column 1, I swap rows 
    # loking at all the permutations from step 2 onwards, but I DON'T
    # apply swaps made at steps 0 and 1.
    for j in range(N-1):
        for i in range(j+1,N):
            p = swap[i]
            L[i,j], L[p,j] = L[p,j], L[i,j]
      
    LU = solveinput(L,A,swap)
    
    return LU


def linsolve_LU(LU,b):
    
    L = LU.lower
    U = LU.upper
    swaps = LU.swaps
       
    N = len(b)
    
    # Applying all swaps to b (can be done at once)
    for i in range(len(swaps)):
        b[i], b[swaps[i]] = b[swaps[i]], b[i]
    
    ######################################################
    # Now solving LUx = b via double backsubstitution
    # First solve Ly = b, to get y. Then solve Ux = y, 
    # to get the desired solutionx 
   
    # Solving Ly = b.
    # Initialize solution vector
    y = np.zeros(N)
    # Gets first solution
    y[0] = b[0]/L[0,0]
    # Proceed forward, line by line
    for i in range(1,N):
        v = np.dot(L[i,0:i],y[0:i])
        y[i] = (b[i] - v)/L[i,i]
    
    # Solving Ux = y
    # Initialize solution vector
    x = np.zeros(N)    
    # Gets last solution, x_(N-1)
    x[N-1] = y[N-1]/U[N-1,N-1]
    # Proceed backward, line by line
    for i in range(N-2,-1,-1):
        v = np.dot(U[i,i+1:N],x[i+1:N])
        #if (i==1): print(i, i+1, N-1, A[i,i+1:N])
        x[i] = (y[i] - v)/U[i,i]
    
    return x

In [ ]:
# Testing example
A = [ [2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]]
A = np.array(A,dtype=float)
#print(A)

b = [-4, 3, 9, 7]
b = np.array(b,dtype=float)
#print(b)

LU = LUdec(A)

#disp = np.round(U,2)
#print('U =', '\n', disp)
#disp = np.round(L,2)
#print('L=', '\n', disp, '\n')

x = linsolve_LU(LU,b)

print('My solution =', x)

In [ ]:
# Cross checking against numpy solver

A = [ [2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]]
A = np.array(A,dtype=float)
#print(A)

b = [-4, 3, 9, 7]
b = np.array(b,dtype=float)
#print(b)

x = solve(A,b)
print('Numpy solution = ', x)

In [ ]:
# Testing example for pivoting

A = [ [0, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]]
A = np.array(A,dtype=float)
#print(A)

b = [-4, 3, 9, 7]
b = np.array(b,dtype=float)
#print(b)

LU = LUdec(A)

x = linsolve_LU(LU,b)

print('My solution =', x)

In [ ]:
A = [ [0, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]]
A = np.array(A,dtype=float)
#print(A)

b = [-4, 3, 9, 7]
b = np.array(b,dtype=float)

y = solve(A,b)
print('Numpy solution =', y)

In [ ]:
# Exploiting LU to solve systems with same A and different b

A_in  = np.array([ [0, 1, 4, 1, 0], [3, 4, -1, -1, 7], [1, -4, 1, 5, -14], [2, -2, 1, 3, -1], [21, -6, -9, 8, 1] ], dtype=float)
b_in = np.array([0, 0, 3, -6, 21],float)    

A = np.copy(A_in)

# Do this only once for any b
LU = LUdec(A)

###########################
b = np.copy(b_in)
x = linsolve_LU(LU,b)
print('My solution =', x)

A = np.copy(A_in)
b = np.copy(b_in)  
y = solve(A,b)
print('Numpy solution =', y, '\n')   

b_in = np.array([1, 7, 102, -6, -49.5],float)    
b = np.copy(b_in)
x = linsolve_LU(LU,b)
print('My solution =', x)

A = np.copy(A_in)
b = np.copy(b_in)  
y = solve(A,b)
print('Numpy solution =', y, '\n')   

### Gauss-Seidel

In [108]:
import numpy as np

def GSeid(A,b,x0,tol):

    # Solving linear systems via Gauss-Seidel method
    
    demomode = False
    if demomode:
        step = 1
    
    # Array size
    N = len(b)
    # Vector containing diagonal elements
    d = np.diag(A)
    # Vector containing inverse of diagonal
    dm1 = (np.diag(A))**(-1)
    
    x = x0
    
    acc = tol + 1.
    while (acc > tol):
    
        # \sum Aij xj - Aii xi
        y = np.matmul(A,x) - np.multiply(x,d)    
        # Gauss-Seidel formula
        x1 = np.multiply(dm1, b - y)
        
        if demomode:
            print('step =', step, 'x = ', x1)
            step += 1
        
        # Calculating accuracy and updating x
        acc = np.max(abs(x1 - x))
        x = x1 
        
    return x

#### Example: Use Gauss-Seidel to solve problem from slide 44 in the "linear algebra" file.

In [109]:
A = np.array([ [ 4, -1, 1], [-1, 4, -2], [1, -2, 4] ],dtype=float)
b = [12.0, -1.0, 5.0]
x0 = [1, 1, 1]
tol = 1e-10

In [110]:
x = GSeid(A,b,x0,tol)

print('The solution is ', x)

The solution is  [3. 1. 1.]


In [121]:
A = np.array([ [ 4, -1, 1, 3], [4, 10, -2, 1], [-2, 4, 14, -5],  [5, -1, 4, 20]],dtype=float)
b = [12.0, -1.0, 5.0, 2.0]
x0 = [1, 1, 1, 1]
tol = 1e-10

In [122]:
x = GSeid(A,b,x0,tol)

print('The solution is ', x)

The solution is  [ 3.20531654 -1.12836656  0.80902413 -0.91955229]


In [123]:
print(np.matmul(A,x), b)

[12. -1.  5.  2.] [12.0, -1.0, 5.0, 2.0]
